development:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "afgnsu"
  #password: "........"
  #要改設定『Google應用程式密碼』=> https://security.google.com/settings/security/apppasswords
  password: "bwkepwjehdxxxxxx"
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "gmail.com"
  authentication: "plain"
  user_name: "myemail@gmail.com"
  password: "1234567890"
  enable_starttls_auto: true
